import type { products } from "./schema";

type SeedProduct = typeof products.$inferInsert;
const image = (name: string) => `/images/${name}.jpg`;
const colors = {
  ruby: { name: "Ruby", hex: "#9B1B30" },
  maroon: { name: "Maroon", hex: "#6B1E2A" },
  emerald: { name: "Emerald", hex: "#0F5132" },
  ivory: { name: "Ivory", hex: "#F1E7D3" },
  blush: { name: "Blush", hex: "#E8B4B8" },
  indigo: { name: "Indigo", hex: "#1F2A44" },
  gold: { name: "Gold", hex: "#C9A24B" },
  noir: { name: "Noir", hex: "#1C1512" },
  marigold: { name: "Marigold", hex: "#E0A21B" },
  saffron: { name: "Saffron", hex: "#E2711D" },
  plum: { name: "Deep Plum", hex: "#4A1E4F" },
  peacock: { name: "Peacock Blue", hex: "#1E5A7A" },
  wine: { name: "Wine", hex: "#722F37" },
  mint: { name: "Mint", hex: "#A9CDB5" },
};

export const extraCategories = [
  { slug: "dupattas", name: "Dupattas", description: "A little more poetry. Handwoven silk, zari borders, and heirloom drapes.", image: image("m12") },
  { slug: "blouses", name: "Blouses", description: "The finishing touch. Brocade blouses, cut and finished with care.", image: image("m05") },
  { slug: "kurta-sets", name: "Kurta Sets", description: "Unhurried elegance in handloom Chanderi and silk cotton.", image: image("m13") },
  { slug: "shawls-stoles", name: "Shawls & Stoles", description: "Wrap yourself in the warmth of Kashmiri needlework.", image: image("m04") },
];

export const extraCollections = [
  { slug: "bridal-vows", name: "The Bridal Vows", description: "For the beginning of forever. Ruby silks, luminous zari, and wedding heirlooms.", image: image("bridal"), featured: true },
  { slug: "temple-gold", name: "Temple & Gold", description: "From Kanchipuram, with devotion. Temple borders and the glow of pure silk.", image: image("m05"), featured: true },
  { slug: "moonlit-drapes", name: "Moonlit Drapes", description: "A little after-dark magic. Fluid georgettes and jewel-toned silks.", image: image("m10"), featured: true },
  { slug: "garden-of-blooms", name: "Garden of Blooms", description: "Petal-soft Chanderi, airy organza, and florals made for slow mornings.", image: image("m06"), featured: true },
  { slug: "indigo-stories", name: "Indigo Stories", description: "A love letter to blue. Ikat geometry and Kashmiri paisley in midnight hues.", image: image("m04"), featured: true },
  { slug: "everyday-poetry", name: "Everyday Poetry", description: "Because ordinary days deserve beautiful things. Easy cottons and considered sets.", image: image("m13"), featured: false },
  { slug: "shubh-deepavali", name: "Shubh Deepavali", description: "Diwali & Dussehra drapes. Diya-glow silks, marigold colour and zari that catches the light.", image: image("m24"), featured: true },
];

const product = (p: SeedProduct): SeedProduct => ({
  category: "sarees",
  tagline: "Handloom heritage · Hand-finished",
  care: "Dry clean only. Store in a breathable muslin wrap.",
  stock: 12,
  rating: 4.8,
  reviewCount: 0,
  isNew: true,
  ...p,
});

export const extraProducts: SeedProduct[] = [
  product({
    slug: "sindoor-bridal-katan-saree", name: "Sindoor Bridal Katan Saree", price: 31500, compareAtPrice: 36000,
    weave: "banarasi", fabric: "Katan Silk", occasion: "wedding", collection: "bridal-vows",
    tagline: "Ruby silk · A vow in gold", work: "Kadhua zari floral jaal", badge: "Bridal Edit", featured: true, stock: 6,
    description: "A bridal drape in deep ruby katan silk, with gold floral jaal across the body and a generous brocade pallu. Made for a day you will remember forever.",
    story: "This design draws on the floral jaal patterns of Varanasi. Individual motifs are woven with separate shuttles in the traditional kadhua technique.",
    colors: [colors.ruby, colors.maroon], images: [image("bridal"), image("silk-maroon")],
  }),
  product({
    slug: "noor-ivory-chanderi-saree", name: "Noor Ivory Chanderi Saree", price: 16800,
    weave: "chanderi", fabric: "Silk Cotton", occasion: "wedding", collection: "bridal-vows",
    tagline: "An ivory wedding · Woven light", work: "Gold zari butis and border", stock: 8,
    description: "Soft ivory silk cotton with luminous zari butis and a delicate gold border. An understated choice for an intimate wedding or civil ceremony.",
    story: "The sheer texture of Chanderi comes from the balance of silk and fine cotton yarns, an enduring craft from Madhya Pradesh.",
    colors: [colors.ivory], images: [image("m13"), image("craft-loom")],
  }),
  product({
    slug: "anaar-brocade-bridal-lehenga", name: "Anaar Brocade Bridal Lehenga", price: 58500,
    category: "lehengas", weave: "banarasi", fabric: "Brocade Silk", occasion: "wedding", collection: "bridal-vows",
    tagline: "Three pieces · One unforgettable moment", work: "Zari brocade and hand finishing", blouse: "Stitched to measure", length: "Lehenga, blouse, and dupatta", stock: 4, badge: "Made to Measure",
    description: "A ruby brocade lehenga, fitted blouse, and zari-edged dupatta. Hand-finished and made to your measurements; allow 4–6 weeks for dispatch.",
    story: "Cut from brocade panels that preserve the continuity of the woven motif, then carefully finished in the atelier.",
    colors: [colors.ruby], images: [image("m03"), image("silk-maroon")],
  }),
  product({
    slug: "gopuram-emerald-kanjivaram-saree", name: "Gopuram Emerald Kanjivaram", price: 27900,
    weave: "kanjivaram", fabric: "Mulberry Silk", occasion: "festive", collection: "temple-gold",
    tagline: "Emerald silk · Temple devotion", work: "Korvai temple border", badge: "Collector's Edit", featured: true,
    description: "Emerald mulberry silk with a temple-inspired contrast border and gold butis. A rich, structured drape for festive celebrations.",
    story: "The gopuram motif echoes the architecture of South Indian temple towers. The contrast border is interlocked using the korvai technique.",
    colors: [colors.emerald, colors.maroon], images: [image("m05"), image("silk-green")],
  }),
  product({
    slug: "mayil-peacock-kanjivaram-saree", name: "Mayil Peacock Kanjivaram", price: 32800,
    weave: "kanjivaram", fabric: "Mulberry Silk", occasion: "wedding", collection: "temple-gold",
    tagline: "Mayura motifs · Jewel-toned silk", work: "Peacock zari butta", stock: 7,
    description: "Peacock-blue silk with a broad gold border and mayura-inspired motifs. A South Indian classic with an expressive, luminous pallu.",
    story: "Peacock motifs are a recurring language in the silk-weaving traditions of Kanchipuram, linking the loom to temple art.",
    colors: [colors.indigo, colors.emerald], images: [image("m04"), image("silk-green")],
  }),
  product({
    slug: "meenakshi-marigold-kanjivaram", name: "Meenakshi Marigold Kanjivaram", price: 23800,
    weave: "kanjivaram", fabric: "Mulberry Silk", occasion: "festive", collection: "temple-gold",
    tagline: "Marigold warmth · Antique zari", work: "Woven zari temple border",
    description: "A warm marigold silk saree with antique-gold zari, created for haldi celebrations and festive mornings.",
    story: "The warmth of marigold is paired with traditional temple-border geometry, a favourite combination across generations.",
    colors: [colors.gold], images: [image("m08"), image("m07")],
  }),
  product({
    slug: "chandni-midnight-georgette-saree", name: "Chandni Midnight Georgette", price: 13800,
    weave: "georgette", fabric: "Georgette", occasion: "evening", collection: "moonlit-drapes",
    tagline: "After-dark elegance · A liquid drape", work: "Antique-gold zari edge", featured: true,
    description: "Midnight georgette, a fluid pallu, and a quiet gold border. An elegant drape for receptions and after-dark gatherings.",
    story: "Contemporary fluid fabric meets a traditional woven edge, bringing the heritage border into a lighter silhouette.",
    colors: [colors.noir, colors.indigo], images: [image("m10"), image("m09")],
  }),
  product({
    slug: "mehfil-wine-crepe-silk-saree", name: "Mehfil Wine Crepe Silk", price: 18500,
    weave: "mysore", fabric: "Crepe Silk", occasion: "evening", collection: "moonlit-drapes",
    tagline: "Dinner-hour silk · A subtle sheen", work: "Slim woven zari border",
    description: "Wine crepe silk that catches the light with every step, edged in a slim line of zari. Pair with a brocade blouse for evening.",
    story: "Crepe yarns lend this silk a softly textured surface and a wonderfully fluid fall.",
    colors: [colors.maroon], images: [image("m09"), image("silk-maroon")],
  }),
  product({
    slug: "gulmohar-floral-organza-saree", name: "Gulmohar Floral Organza", price: 12400,
    weave: "organza", fabric: "Organza", occasion: "day", collection: "garden-of-blooms",
    tagline: "Petal-soft · Garden-party grace", work: "Floral hand embroidery", featured: true,
    description: "A softly embroidered organza drape with floral details and an airy pallu, made for garden weddings and sunlit celebrations.",
    story: "Petals and winding stems are interpreted in fine needlework along the edge of a sheer organza drape.",
    colors: [colors.blush, colors.ivory], images: [image("m15"), image("m06")],
  }),
  product({
    slug: "gulaab-blush-chanderi-saree", name: "Gulaab Blush Chanderi", price: 7800,
    weave: "chanderi", fabric: "Silk Cotton", occasion: "day", collection: "garden-of-blooms",
    tagline: "Blush pink · Woven air", work: "Fine zari butis",
    description: "Blush-pink Chanderi silk cotton with scattered zari butis. Easy to wear, light to carry, and quietly festive.",
    story: "A celebration of Chanderi's almost transparent silk-cotton texture, often described as woven air.",
    colors: [colors.blush], images: [image("m06"), image("m12")],
  }),
  product({
    slug: "neel-indigo-ikat-saree", name: "Neel Indigo Ikat Saree", price: 21900,
    weave: "patola", fabric: "Pure Silk", occasion: "evening", collection: "indigo-stories",
    tagline: "Indigo geometry · Thread by thread", work: "Ikat-inspired geometric weaving", badge: "Indigo Edit",
    description: "A deep-blue silk saree with geometric motifs inspired by the ikat traditions of Gujarat. Refined colour, expressive pattern, and a soft gold edge.",
    story: "Ikat is a language of pattern created through yarn preparation and the careful alignment of threads at the loom.",
    colors: [colors.indigo], images: [image("m04"), image("m16")],
  }),
  product({
    slug: "sanganer-everyday-handloom-cotton", name: "Sanganer Everyday Cotton", price: 3490,
    weave: "cotton", fabric: "Handloom Cotton", occasion: "casual", collection: "everyday-poetry",
    tagline: "Easy mornings · Handloom comfort", work: "Block-print floral details", care: "Gentle hand wash in cold water. Dry in shade.", stock: 30,
    description: "Breathable handloom cotton with charming floral details. For workdays, café afternoons, and moments that need no occasion.",
    story: "The simplicity of a cotton drape lets the rhythm of the handloom and the character of hand printing speak.",
    colors: [colors.ivory, colors.blush], images: [image("m11"), image("m13")],
  }),
  product({
    slug: "vasant-ivory-chanderi-kurta-set", name: "Vasant Ivory Chanderi Set", price: 11800,
    category: "kurta-sets", weave: "chanderi", fabric: "Silk Cotton", occasion: "day", collection: "garden-of-blooms",
    tagline: "Kurta, trousers & dupatta · Softly festive", work: "Woven zari butis", blouse: "Not applicable", length: "Three-piece kurta set", featured: true, badge: "New Category",
    description: "An ivory Chanderi kurta with matching trousers and a sheer blush dupatta. A light, polished three-piece set for intimate celebrations.",
    story: "Fine silk cotton keeps the silhouette airy while woven gold butis bring a touch of handloom occasionwear.",
    colors: [colors.ivory], images: [image("m13"), image("craft-loom")],
  }),
  product({
    slug: "savera-handloom-kurta-set", name: "Savera Handloom Kurta Set", price: 8600,
    category: "kurta-sets", weave: "cotton", fabric: "Cotton Silk", occasion: "casual", collection: "everyday-poetry",
    tagline: "Thoughtful essentials · Three-piece set", work: "Woven butis and hand-finished seams", blouse: "Not applicable", length: "Kurta, trousers, and dupatta",
    description: "An easy ivory kurta set with a soft dupatta and straight trousers. Considered essentials for everyday elegance.",
    story: "Traditional woven motifs find a home in an everyday silhouette, cut for movement and comfort.",
    colors: [colors.ivory], images: [image("m11"), image("m13")],
  }),
  product({
    slug: "shahi-maroon-banarasi-dupatta", name: "Shahi Banarasi Silk Dupatta", price: 6900,
    category: "dupattas", weave: "banarasi", fabric: "Katan Silk", occasion: "wedding", collection: "bridal-vows",
    tagline: "Maroon silk · A regal finishing touch", work: "Gold zari butis and brocade border", blouse: "Not applicable", length: "2.4 m × 0.9 m", featured: true, badge: "Handwoven",
    description: "A maroon Banarasi silk dupatta with gold butis and a generous brocade border. Drape over ivory, layer with a lehenga, or treasure as a gift.",
    story: "A smaller canvas for the intricacy of Banarasi weaving, carrying the same timeless floral border language.",
    colors: [colors.maroon], images: [image("m12"), image("silk-maroon")],
  }),
  product({
    slug: "gulnaar-zari-silk-dupatta", name: "Gulnaar Zari Silk Dupatta", price: 8900,
    category: "dupattas", weave: "banarasi", fabric: "Pure Silk", occasion: "festive", collection: "heirloom-edit",
    tagline: "A legacy in miniature · Gold brocade", work: "Brocade zari border", blouse: "Not applicable", length: "2.5 m × 0.9 m",
    description: "A richly textured silk dupatta in maroon and gold, designed to bring an heirloom accent to the simplest outfit.",
    story: "Traditional butis and an ornate border make this a versatile piece of woven heritage.",
    colors: [colors.maroon, colors.gold], images: [image("m16"), image("silk-maroon")],
  }),
  product({
    slug: "maharani-emerald-brocade-blouse", name: "Maharani Emerald Brocade Blouse", price: 5400,
    category: "blouses", weave: "banarasi", fabric: "Brocade Silk", occasion: "festive", collection: "temple-gold",
    tagline: "Emerald brocade · Made to measure", work: "Gold butis, silk piping", blouse: "Stitched to measure", length: "Blouse length: 14–16 inches", badge: "Made to Measure",
    description: "An emerald brocade blouse with delicate gold butis, a boat neckline, and clean silk piping. Made to your measurements in the atelier.",
    story: "A traditional woven brocade is carefully cut so its butis remain balanced across the finished blouse.",
    colors: [colors.emerald], images: [image("m05"), image("silk-green")],
  }),
  product({
    slug: "royal-zari-brocade-blouse", name: "Royal Zari Brocade Blouse", price: 6200,
    category: "blouses", weave: "banarasi", fabric: "Brocade Silk", occasion: "wedding", collection: "heirloom-edit",
    tagline: "The final detail · Couture finishing", work: "Woven butis and gold edging", blouse: "Stitched to measure", length: "Made-to-measure blouse",
    description: "A classic emerald blouse in woven brocade, finished with delicate gold edging and a refined fitted silhouette.",
    story: "The blouse completes the drape: a small, beautifully finished canvas for traditional zari work.",
    colors: [colors.emerald], images: [image("m03"), image("craft-loom")],
  }),
  product({
    slug: "neelam-sozni-pashmina-shawl", name: "Neelam Sozni Pashmina Shawl", price: 24500,
    category: "shawls-stoles", weave: "kashmiri", fabric: "Fine Wool", occasion: "evening", collection: "indigo-stories",
    tagline: "Kashmiri paisley · Indigo warmth", work: "Sozni-inspired needle embroidery", blouse: "Not applicable", length: "2 m × 1 m", featured: true, stock: 6, badge: "Winter Heirloom",
    description: "An indigo fine-wool shawl with ornate paisley borders in antique-gold and terracotta tones. A warm companion for winter celebrations.",
    story: "The boteh paisley and delicate needlework draw on the long textile traditions of the Kashmir valley.",
    colors: [colors.indigo], images: [image("m04"), image("m04")],
  }),
  product({
    slug: "kashmir-midnight-paisley-stole", name: "Kashmir Midnight Paisley Stole", price: 12800,
    category: "shawls-stoles", weave: "kashmiri", fabric: "Fine Wool", occasion: "evening", collection: "moonlit-drapes",
    tagline: "A midnight wrap · A timeless gift", work: "Paisley embroidered border", blouse: "Not applicable", length: "1.9 m × 0.7 m", stock: 10,
    description: "A refined indigo stole with paisley needlework along the border, made for cool evenings and thoughtful gifting.",
    story: "Kashmiri embroidery tells its stories in miniature, with vines and boteh motifs moving quietly around each border.",
    colors: [colors.indigo], images: [image("m10"), image("craft-loom")],
  }),
  // --- Festival & variety expansion: new model imagery across the weave families ---
  product({
    slug: "deepavali-plum-banarasi-saree", name: "Deepavali Plum Banarasi Saree", price: 21400, compareAtPrice: 25900,
    weave: "banarasi", fabric: "Katan Silk", occasion: "festive", collection: "shubh-deepavali",
    tagline: "Diya glow · Zari that catches light", work: "Gold zari buti with kadhua border",
    badge: "Diwali Edit", featured: true, stock: 10, rating: 4.9, reviewCount: 32,
    description: "A deep-plum katan silk Banarasi with dense gold zari butis and a broad kadhua border. Woven for Diwali evenings when the diyas are lit and the zari answers back.",
    story: "Woven in Varanasi over three weeks. The plum dye is deepened twice so the silk holds its colour under warm lamplight, and every buti is set with its own shuttle.",
    colors: [colors.plum, colors.maroon, colors.gold], images: [image("m24"), image("m17")],
  }),
  product({
    slug: "marigold-kanjivaram-festive-saree", name: "Marigold Kanjivaram Festive Saree", price: 23900, compareAtPrice: 27400,
    weave: "kanjivaram", fabric: "Mulberry Silk", occasion: "festive", collection: "shubh-deepavali",
    tagline: "Saffron silk · Festival devotion", work: "Korvai temple border in gold zari",
    badge: "Diwali Edit", featured: true, stock: 8, rating: 4.9, reviewCount: 27,
    description: "A saffron-marigold Kanjivaram in pure mulberry silk with a gold temple border and a wide zari pallu. The colour of marigold garlands and Dussehra mornings.",
    story: "Body and border are woven separately in Kanchipuram and interlocked by hand with the korvai technique, so the temple edge never separates from the silk.",
    colors: [colors.saffron, colors.marigold, colors.ruby], images: [image("m25"), image("m18")],
  }),
  product({
    slug: "festive-maroon-gold-embroidered-saree", name: "Festive Maroon & Gold Saree", price: 18900, compareAtPrice: 22400,
    weave: "banarasi", fabric: "Silk Blend", occasion: "festive", collection: "shubh-deepavali",
    tagline: "Celebration colour · Hand-finished", work: "Gold zari embroidery and border",
    badge: "Bestseller", featured: true, stock: 12, rating: 4.8, reviewCount: 45,
    description: "A maroon drape with warm gold embroidery that moves the way festival light does. Comfortable enough for a long evening of puja, family and photographs.",
    story: "Finished by hand in our atelier: the embroidered border is set after the weave comes off the loom, one panel at a time.",
    colors: [colors.maroon, colors.gold, colors.ruby], images: [image("m28"), image("m17")],
  }),
  product({
    slug: "royal-maroon-banarasi-kadhua-saree", name: "Royal Maroon Banarasi Kadhua Saree", price: 25900, compareAtPrice: 29900,
    weave: "banarasi", fabric: "Katan Silk", occasion: "festive", collection: "shubh-deepavali",
    tagline: "Deep maroon · Brocade grandeur", work: "Pure zari kadhua brocade",
    featured: true, stock: 7, rating: 4.9, reviewCount: 38,
    description: "An opulent deep-maroon Banarasi with intricate gold zari brocade across the body and a full-width brocade pallu. A statement drape for the biggest evenings of the year.",
    story: "Every motif is woven as a separate unit, which is why the reverse of a true kadhua saree shows those signature floating threads.",
    colors: [colors.maroon, colors.gold], images: [image("m17"), image("m24")],
  }),
  product({
    slug: "emerald-kanjivaram-temple-festive-saree", name: "Emerald Kanjivaram Temple Saree", price: 26400,
    weave: "kanjivaram", fabric: "Mulberry Silk", occasion: "festive", collection: "temple-gold",
    tagline: "Emerald silk · Gold temple checks", work: "Gold temple border and checks",
    badge: "Trending", stock: 9, rating: 4.9, reviewCount: 29,
    description: "Royal emerald mulberry silk with a gold temple border and fine zari checks. Structured, lustrous and unmistakably South Indian.",
    story: "The temple border repeats a gopuram motif drawn on paper first, then translated to the loom punch card.",
    colors: [colors.emerald, colors.gold], images: [image("m18"), image("m21")],
  }),
  product({
    slug: "mint-chanderi-zari-booti-saree", name: "Mint Chanderi Zari Booti Saree", price: 12400, compareAtPrice: 14900,
    weave: "chanderi", fabric: "Silk Cotton", occasion: "day", collection: "garden-of-blooms",
    tagline: "Featherlight · Sheer zari", work: "Fine gold zari booti",
    stock: 14, rating: 4.7, reviewCount: 21,
    description: "A pastel-mint Chanderi silk cotton scattered with fine gold booti motifs. Woven air — light enough for a long festive day, dressed enough for the evening.",
    story: "Chanderi's glassy transparency comes from the balance of silk warp and fine cotton weft, a craft kept alive by a small cluster of weaver families.",
    colors: [colors.mint, colors.ivory, colors.gold], images: [image("m19"), image("m22")],
  }),
  product({
    slug: "gharchola-red-bandhani-saree", name: "Gharchola Red Bandhani Saree", price: 15900, compareAtPrice: 18900,
    weave: "bandhani", fabric: "Silk", occasion: "festive", collection: "festival-of-colour",
    tagline: "Knots of celebration · Gujarati craft", work: "Hand-tied bandhani dots",
    badge: "Festival Edit", stock: 11, rating: 4.8, reviewCount: 34,
    description: "A vibrant red and yellow gharchola with thousands of hand-tied bandhani dots and a gold check grid. A traditional Gujarati drape for weddings and festivals.",
    story: "Each tiny dot is pinched and tied by hand before dyeing — a single saree carries tens of thousands of knots, all undone again after the colour sets.",
    colors: [colors.ruby, colors.marigold, colors.saffron], images: [image("m20"), image("m28")],
  }),
  product({
    slug: "patola-magenta-green-silk-saree", name: "Patola Magenta & Green Silk Saree", price: 42000, compareAtPrice: 48000,
    weave: "patola", fabric: "Mulberry Silk", occasion: "wedding", collection: "heirloom-edit",
    tagline: "Double ikat · Collector's weave", work: "Resist-dyed double ikat",
    badge: "Limited Edition", stock: 3, rating: 5, reviewCount: 18,
    description: "A Patan Patola in magenta and deep green, resist-dyed on both warp and weft so the elephant-and-parrot motifs align thread by thread. Months of work in one drape.",
    story: "Patola is the most demanding of the double-ikat traditions: every thread is dyed to its exact position before weaving, leaving no room for correction at the loom.",
    colors: [colors.ruby, colors.emerald, colors.peacock], images: [image("m21"), image("m25")],
  }),
  product({
    slug: "blush-organza-sequin-saree", name: "Blush Organza Sequin Saree", price: 17900, compareAtPrice: 21500,
    weave: "organza", fabric: "Organza", occasion: "evening", collection: "moonlit-drapes",
    tagline: "Sheer modern muse · Pearl & sequin", work: "Pearl and sequin embroidery",
    featured: true, stock: 10, rating: 4.8, reviewCount: 26,
    description: "A sheer blush organza scattered with pearl and sequin embroidery that catches every light in the room. Contemporary, airy and made for the after-party.",
    story: "The embroidery is worked on a stretched frame in Lucknow, then the finished panel is hand-applied to the organza to keep the drape whisper-light.",
    colors: [colors.blush, colors.ivory], images: [image("m22"), image("m19")],
  }),
  product({
    slug: "wine-georgette-sequin-saree", name: "Wine Georgette Sequin Saree", price: 14500, compareAtPrice: 17400,
    weave: "georgette", fabric: "Georgette", occasion: "evening", collection: "moonlit-drapes",
    tagline: "Fluid drape · Evening gold", work: "Subtle gold sequin work",
    stock: 13, rating: 4.7, reviewCount: 30,
    description: "A flowing wine-red georgette with delicate gold sequin work and a soft zari border. It pleats beautifully and moves like liquid under lights.",
    story: "Georgette's crinkled crepe texture is created by tightly twisting the yarn before weaving, which is why it holds a pleat so well.",
    colors: [colors.wine, colors.maroon, colors.gold], images: [image("m23"), image("m28")],
  }),
  product({
    slug: "ivory-gold-tissue-silk-saree", name: "Ivory & Gold Tissue Silk Saree", price: 19600, compareAtPrice: 22900,
    weave: "banarasi", fabric: "Tissue Silk", occasion: "wedding", collection: "bridal-vows",
    tagline: "Luminous ivory · Woven gold", work: "Delicate zari tissue weave",
    stock: 8, rating: 4.9, reviewCount: 22,
    description: "A luminous ivory tissue silk with a fine all-over zari weave that gives the whole drape a soft gold sheen. A serene choice for an intimate or daytime wedding.",
    story: "Tissue silk is woven with a fine metallic zari weft, which is what gives the fabric its inner glow rather than a surface shine.",
    colors: [colors.ivory, colors.gold], images: [image("m26"), image("m22")],
  }),
  product({
    slug: "royal-blue-tussar-zari-saree", name: "Royal Blue Tussar Zari Saree", price: 16900,
    weave: "tussar", fabric: "Tussar Silk", occasion: "festive", collection: "indigo-stories",
    tagline: "Wild silk · Golden booti", work: "Gold booti with wide zari pallu",
    stock: 10, rating: 4.8, reviewCount: 19,
    description: "A royal-blue Tussar silk with golden booti motifs and a wide zari pallu. Tussar's natural texture gives the colour real depth.",
    story: "Tussar is a wild silk with a naturally golden cast, spun from cocoons gathered in the forests of Bhagalpur and its surrounds.",
    colors: [colors.peacock, colors.indigo, colors.gold], images: [image("m27"), image("m21")],
  }),
  // --- Glamour capsule: evening & festive drapes on new campaign imagery ---
  product({
    slug: "noor-wine-satin-silk-saree", name: "Noor Wine Satin Silk Saree", price: 18400, compareAtPrice: 21900,
    weave: "georgette", fabric: "Satin Silk", occasion: "evening", collection: "moonlit-drapes",
    tagline: "Liquid wine · Modern drape", work: "Satin sheen with hand-finished border",
    badge: "New Glam", featured: true, stock: 9, rating: 4.8, reviewCount: 12,
    description: "A lustrous wine satin silk with a modern silhouette and a hand-finished border. Cut for the spotlight — an evening drape that holds its sheen under every light.",
    story: "The satin weave takes its deep colour from a double-dye bath, then the border is set by hand so the hem falls in a clean liquid line.",
    colors: [colors.wine, colors.maroon, colors.ruby], images: [image("m29"), image("m23")],
  }),
  product({
    slug: "raat-black-sequin-georgette-saree", name: "Raat Black Sequin Georgette Saree", price: 19900, compareAtPrice: 23500,
    weave: "georgette", fabric: "Georgette", occasion: "evening", collection: "moonlit-drapes",
    tagline: "After-dark sparkle · Editorial", work: "Gold sequin on sheer georgette",
    badge: "New Glam", featured: true, stock: 8, rating: 4.9, reviewCount: 15,
    description: "A sheer black georgette scattered with gold sequins that catch every flash. Made for after-dark celebrations and the photographs that follow.",
    story: "Sequins are applied by hand on a stretched frame, spaced so the sheer georgette keeps its fluidity and the shimmer moves as you do.",
    colors: [colors.noir, colors.gold], images: [image("m30"), image("m23")],
  }),
  product({
    slug: "nagmas-emerald-silk-saree", name: "Naghma Emerald Silk Saree", price: 21400, compareAtPrice: 24900,
    weave: "mysore", fabric: "Mulberry Silk", occasion: "festive", collection: "temple-gold",
    tagline: "Emerald glow · Golden hour", work: "Gold zari border on lustrous silk",
    badge: "New Glam", featured: true, stock: 10, rating: 4.9, reviewCount: 11,
    description: "A shimmering emerald mulberry silk with a gold zari border and a fluid, glossy drape. Colour with real depth — richest under warm evening light.",
    story: "Woven in Mysuru from pure mulberry crepe, the silk's natural sheen needs no embellishment; the zari border does the talking.",
    colors: [colors.emerald, colors.gold], images: [image("m31"), image("m18")],
  }),
  product({
    slug: "sunheri-banarasi-orange-saree", name: "Sunheri Banarasi Orange Saree", price: 22900, compareAtPrice: 26400,
    weave: "banarasi", fabric: "Katan Silk", occasion: "festive", collection: "shubh-deepavali",
    tagline: "Burnt orange · Festival gold", work: "Gold zari buti on katan silk",
    badge: "Diwali Edit", featured: true, stock: 7, rating: 4.9, reviewCount: 13,
    description: "A burnt-orange katan silk Banarasi with gold zari butis and a modern sleeveless-blouse-ready body. Bold festive colour with heritage weave.",
    story: "The orange is dyed deep so the gold zari sits against warmth rather than brightness — a Diwali-evening colour, not a noon colour.",
    colors: [colors.saffron, colors.marigold, colors.gold], images: [image("m32"), image("m24")],
  }),
  product({
    slug: "neel-rimlight-silk-saree", name: "Neel Rimlight Silk Saree", price: 20900,
    weave: "mysore", fabric: "Silk", occasion: "evening", collection: "moonlit-drapes",
    tagline: "Royal blue · Silver zari", work: "Silver zari on royal-blue silk",
    featured: true, stock: 9, rating: 4.8, reviewCount: 9,
    description: "A royal-blue silk with silver zari that reads almost metallic in low light. A dramatic evening drape with a quietly modern attitude.",
    story: "Silver zari against deep blue is a classic Mysore pairing — the metallic thread picks up ambient colour, so the saree shifts with the room.",
    colors: [colors.peacock, colors.indigo], images: [image("m33"), image("m27")],
  }),
];

export const extraWeaves = [
  { slug: "kashmiri", name: "Kashmiri Needlework", region: "Kashmir Valley", tagline: "A story in every stitch", story: "Paisley borders and fine needlework, inspired by the textile traditions of Kashmir.", image: image("m04") },
];
